
# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft5x0x_af168/include/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft5x0x_af168/include/$(CONFIG_FT5X0X_FIRMWARE)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  ft5x0x_driver.o
obj-y	+=  ft5x0x_upgrade.o
obj-y	+=  focaltech_ctl.o
obj-y	+=  focaltech_ex_fun.o

